### ISSUE TITLE
没啥意义啊

### ISSUE THREAD

**Issue by jsLyLeeHi** [154305/react-pinia-store#1]
这本质不就是在useState上做了一下二次封装吗？

**Comment by 154305** [comment]
你要这样说也没办法，react本质不也是在js基础上做的库吗，原理是这么个原理，但是能不能解决问题才是关键

**Comment by jsLyLeeHi** [comment]
确实没啥意义啊，useState本来就能监听数据更新，你还用proxy再去监听，你这搞得显得有点多余。
